### ISSUE TITLE
Question: An isolated way to use Khmer Angkor character reordering function from Keyman

### ISSUE THREAD

**Issue by seanghay** [mcdurdin/khmer-syllable-example#1]
Good morning, Marc!

I would like to get some ideas from you related to the usage of Khmer Angkor keyboard's character reorder/normalize function. Basically, something like this (https://github.com/sillsdev/khmer-character-specification/blob/master/python/scripts/khnormal) but in JavaScript.

Let's say I have a raw text string:
```js
const text = "ស្រ្តី" // 0x179f 0x17d2 0x179a 0x17d2 0x178f 0x17b8

const result = normalize(text)

// => "ស្ត្រី" 0x179f 0x17d2 0x178f 0x17d2 0x179a 0x17b8
```

Basically, I want to use the `normalize()` function from Khmer Angkor keyman keyboard.

**Comment by mcdurdin** [comment]
Sorry for long delay in replying -- I have been away and am now slowly catching up on the backlog.

We have a Python module but not currently anything in Javascript. See [convert.ភាសាខ្មែរ​.com](https://convert.xn--j2e7beiw1lb2hqg.com/) for a live example (this site is just about to be launched).

Source for the conversion tool is at https://github.com/sillsdev/khmer-character-specification/tree/master/python/scripts

We would certainly welcome a translation of the Python code to a Javascript module!

@MakaraSok @mhosken and @Nnyny may also have thoughts on this!

**Comment by seanghay** [comment]
Thanks for the response, @mcdurdin!

**Comment by mcdurdin** [comment]
@seanghay please note two bugs identified in khnormal: 

* https://github.com/sillsdev/khmer-character-specification/issues/10
* https://github.com/sillsdev/khmer-character-specification/issues/12

I also have a draft typescript module now which I hope to publish to npm once those two bugs are addressed

**Comment by seanghay** [comment]
Thank you @mcdurdin for pointing this out! Honestly, I have heavily used `khnormal` script throughout my Khmer text-to-speech and other projects. If there is any test suites that I run and validate, I'll definitely help to fix those bugs.
